# Generated by Django 4.0.3 on 2023-02-23 13:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Раздел для видео')),
            ],
            options={
                'verbose_name': 'Раздел видео',
                'verbose_name_plural': 'Разделы видео',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название видео')),
                ('description', models.TextField(blank=True, verbose_name='Описание видео')),
                ('preview', models.ImageField(upload_to='athletes/', verbose_name='Превью видео')),
                ('link_video', models.CharField(max_length=255, verbose_name='Ссылка на видео S3')),
                ('date_added', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время публикации видео')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_video', to='items.categoryvideos', verbose_name='Раздел видео')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видеохостинг',
                'ordering': ('-date_added',),
            },
        ),
    ]
