# Generated by Django 4.0.3 on 2023-05-16 22:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Роль участника команды')),
                ('date_added', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Роль участника',
                'verbose_name_plural': 'Роли участника команды',
                'ordering': ('-date_added',),
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя фамилия участника')),
                ('description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('preview', models.ImageField(upload_to='team/', verbose_name='Фотография участника')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='Ссылка на hh')),
                ('date_added', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время публикации видео')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_team', to='items.categoryteam', verbose_name='Роль участника')),
            ],
            options={
                'verbose_name': 'Участника',
                'verbose_name_plural': 'Команда',
                'ordering': ('-date_added',),
            },
        ),
        migrations.RemoveField(
            model_name='video',
            name='category',
        ),
        migrations.DeleteModel(
            name='CategoryVideos',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
