# Generated by Django 4.0.3 on 2023-05-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_categoryteam_team_remove_video_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryteam',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
