# Generated by Django 4.0.3 on 2023-05-22 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_categoryteam_date_added_alter_team_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, verbose_name='Ссылка на страницу')),
                ('title', models.CharField(max_length=255, verbose_name='Название программы')),
                ('main_photo', models.ImageField(upload_to='programms/', verbose_name='Основная фотография')),
                ('small_disc', models.TextField(verbose_name='Коротко о программе')),
                ('morning', models.TextField(verbose_name='Утро (Описание)')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Программа',
                'verbose_name_plural': 'Программы',
                'ordering': ('-date_added',),
            },
        ),
        migrations.CreateModel(
            name='Smena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_id', models.IntegerField(verbose_name='Номер смены')),
                ('price', models.IntegerField(verbose_name='Стоимость за смену')),
                ('date_start', models.DateField(verbose_name='Дата старта мероприятия')),
                ('date_end', models.DateField(verbose_name='Дата конца мероприятия')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('programm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programm_smena', to='items.programms', verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'Смена',
                'verbose_name_plural': 'Смены',
                'ordering': ('-date_added',),
            },
        ),
    ]
