# Generated by Django 4.0.3 on 2023-05-23 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_programms_smena'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smena',
            old_name='number_id',
            new_name='number',
        ),
    ]
