# Generated by Django 4.0.3 on 2023-05-25 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_rename_number_id_smena_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('data_uchast', models.DateField(verbose_name='Дата рождения участника')),
                ('data_parent', models.DateField(verbose_name='Дата родителя, представителя участника')),
                ('primechanie', models.CharField(max_length=255, verbose_name='Примечание')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('dop_phone', models.CharField(max_length=255, verbose_name='Доп телефон')),
                ('info_title', models.CharField(max_length=255, verbose_name='Откуда узнали о нас')),
                ('programm_info', models.CharField(max_length=255, verbose_name='Программа')),
                ('data_smeni', models.CharField(max_length=255, verbose_name='Дата заезда')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Бронь',
                'verbose_name_plural': 'Брони',
                'ordering': ('-date_added',),
            },
        ),
    ]
