# Generated by Django 4.0.3 on 2023-05-25 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_reserve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='data_parent',
            field=models.CharField(max_length=255, verbose_name='ФИО представителя участника'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='fio',
            field=models.CharField(max_length=255, verbose_name='ФИО участника'),
        ),
    ]
