# Generated by Django 4.0.3 on 2023-05-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_alter_reserve_data_parent_alter_reserve_fio'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='email',
            field=models.CharField(default=1, max_length=255, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserve',
            name='dop_phone',
            field=models.CharField(blank=True, max_length=255, verbose_name='Доп телефон'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='primechanie',
            field=models.CharField(blank=True, max_length=255, verbose_name='Примечание'),
        ),
    ]
