# Generated by Django 4.0.3 on 2023-09-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_reserve_email_alter_reserve_dop_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programms',
            name='morning',
        ),
        migrations.AddField(
            model_name='programms',
            name='age_main',
            field=models.CharField(default=1, max_length=255, verbose_name='Возраст на главной'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programms',
            name='price_main',
            field=models.CharField(default=1, max_length=255, verbose_name='Цена на главной'),
            preserve_default=False,
        ),
    ]
