# Generated by Django 4.0.3 on 2023-09-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_remove_programms_morning_programms_age_main_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagsProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Тэг')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Тэг программ',
                'verbose_name_plural': 'Тэг програмы',
                'ordering': ('-date_added',),
            },
        ),
        migrations.AddField(
            model_name='programms',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags_prog', to='items.tagsprogram', verbose_name='Тэги'),
        ),
    ]
