# Generated by Django 4.0.3 on 2023-09-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_tagsprogram_programms_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programms',
            name='tag',
        ),
        migrations.AddField(
            model_name='programms',
            name='tags_prog',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags_prog_rel', to='items.tagsprogram', verbose_name='Тэги'),
        ),
    ]
