# Generated by Django 4.0.3 on 2023-09-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_remove_programms_tag_programms_tags_prog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSoloSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('img', models.ImageField(upload_to='image/', verbose_name='Фотография')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Карусель на главной',
                'verbose_name_plural': 'Карусель на главной',
                'ordering': ('-date_added',),
            },
        ),
        migrations.AlterField(
            model_name='programms',
            name='main_photo',
            field=models.ImageField(upload_to='image/programm/', verbose_name='Основная фотография'),
        ),
        migrations.AlterField(
            model_name='team',
            name='preview',
            field=models.ImageField(upload_to='image/team/', verbose_name='Фотография участника'),
        ),
    ]
