# Generated by Django 4.0.3 on 2023-09-07 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_mainsoloslider_alter_programms_main_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainGalery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('img', models.ImageField(upload_to='image/', verbose_name='Фотография')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Галерея на главной',
                'verbose_name_plural': 'Галерея на главной',
                'ordering': ('-date_added',),
            },
        ),
    ]
