# Generated by Django 4.0.3 on 2023-09-08 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_maingalery'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockImgSmall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('img', models.ImageField(upload_to='image/', verbose_name='Фотография')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Коротко о программе (фото)',
                'verbose_name_plural': 'Коротко о программе (фото)',
                'ordering': ('-date_added',),
            },
        ),
        migrations.CreateModel(
            name='BlockTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('img', models.ImageField(upload_to='image/', verbose_name='Фотография')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Что ждет ребенка (блоки)',
                'verbose_name_plural': 'Что ждет ребенка (блоки)',
                'ordering': ('-date_added',),
            },
        ),
        migrations.CreateModel(
            name='TagsTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Тэг')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Тэги (Что ждет подростка?)',
                'verbose_name_plural': 'Тэги (Что ждет подростка?)',
                'ordering': ('-date_added',),
            },
        ),
        migrations.CreateModel(
            name='LiderUspesniyStart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название программы')),
                ('small_disc', models.TextField(verbose_name='Коротко о программе (Описание)')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('blockTimes', models.ManyToManyField(blank=True, null=True, related_name='template_lider_usp', to='items.blocktimes', verbose_name='Что ждет ребенка (блоки)')),
                ('imagesSmall', models.ManyToManyField(blank=True, null=True, related_name='imgs_lider_start', to='items.blockimgsmall', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Шаблон (Лидер Усешный Старт)',
                'verbose_name_plural': 'Шаблон (Лидер Усешный Старт)',
                'ordering': ('-date_added',),
            },
        ),
        migrations.AddField(
            model_name='blocktimes',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tag_sl', to='items.tagstimes', verbose_name='Тэги'),
        ),
    ]
