# Generated by Django 4.0.3 on 2023-09-08 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_blockimgsmall_blocktimes_tagstimes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('img', models.ImageField(upload_to='image/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Эвенты блоки (Шаблон)',
                'verbose_name_plural': 'Эвенты блоки (Шаблон)',
            },
        ),
        migrations.CreateModel(
            name='BlockImgsTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('img', models.ImageField(upload_to='image/', verbose_name='Фотография')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Команда лагеря (фото)',
                'verbose_name_plural': 'Команда лагеря (фото)',
                'ordering': ('-date_added',),
            },
        ),
        migrations.CreateModel(
            name='BlockPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('img', models.ImageField(blank=True, upload_to='image/', verbose_name='Фотография')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Место проведения блоки (Шаблон)',
                'verbose_name_plural': 'Место проведения блоки (Шаблон)',
            },
        ),
        migrations.CreateModel(
            name='ImagesPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('img', models.ImageField(upload_to='image/', verbose_name='Фотография')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Место проведения программы (фото)',
                'verbose_name_plural': 'Место проведения программы (фото)',
                'ordering': ('-date_added',),
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.IntegerField(choices=[(0, 'Лидер - успешный старт. Лето'), (1, 'Лидер - шаг вперед'), (2, 'Галилео кидс'), (3, 'Лидер в кадре'), (4, 'Выпускной'), (5, 'Конный лагерь. Horse paradise')], default=0, verbose_name='Шаблон')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название программы')),
                ('main_photo', models.ImageField(upload_to='image/programm/', verbose_name='Основная фотография')),
                ('small_disc', models.TextField(blank=True, verbose_name='Коротко о программе (Описание)')),
                ('titleTimes', models.CharField(blank=True, max_length=255, verbose_name='Что ждет подростка в лагере? (Название)')),
                ('titleTemplate', models.CharField(blank=True, max_length=255, verbose_name='Команда лагеря (Название)')),
                ('descriptionTemplateFirst', models.CharField(blank=True, max_length=255, verbose_name='Команда (Описание 1)')),
                ('descriptionTemplateSesond', models.CharField(blank=True, max_length=255, verbose_name='Команда (Описание 1)')),
                ('placeTitle', models.CharField(blank=True, max_length=255, verbose_name='Место проведения программы')),
                ('placeDescription', models.TextField(blank=True, verbose_name='Коротко о программе (Описание)')),
                ('placeInfoFt', models.CharField(blank=True, max_length=255, verbose_name='Где находится?')),
                ('placeInfoSnd', models.CharField(blank=True, max_length=255, verbose_name='Проживание')),
                ('placeInfoTh', models.CharField(blank=True, max_length=255, verbose_name='В номере')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('imgsPlace', models.ManyToManyField(blank=True, related_name='imgs_place', to='items.imagesplace', verbose_name='Фото (Место проведения)')),
            ],
            options={
                'verbose_name': 'Шаблоны',
                'verbose_name_plural': 'Шаблоны',
                'ordering': ('-date_added',),
            },
        ),
        migrations.AlterModelOptions(
            name='tagstimes',
            options={'ordering': ('-date_added',), 'verbose_name': 'Тэги (Шаблон)', 'verbose_name_plural': 'Тэги (Шаблоны)'},
        ),
        migrations.AddField(
            model_name='programms',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Черновик, если (окно заполнено, то не отображается)'),
        ),
        migrations.AlterField(
            model_name='blocktimes',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='blocktimes',
            name='img',
            field=models.ImageField(blank=True, upload_to='image/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='blocktimes',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tagsTimes', to='items.tagstimes', verbose_name='Тэги'),
        ),
        migrations.DeleteModel(
            name='LiderUspesniyStart',
        ),
        migrations.AddField(
            model_name='blockplace',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tagsPlace', to='items.tagstimes', verbose_name='Тэги'),
        ),
        migrations.AddField(
            model_name='blockplace',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tplace', to='items.template', verbose_name='Шаблон'),
        ),
        migrations.AddField(
            model_name='blockimgsteam',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images_team', to='items.template', verbose_name='Шаблон'),
        ),
        migrations.AddField(
            model_name='blockevents',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bl_events', to='items.template', verbose_name='Шаблон'),
        ),
        migrations.AddField(
            model_name='blockimgsmall',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images_disc', to='items.template', verbose_name='Шаблон'),
        ),
        migrations.AddField(
            model_name='blocktimes',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bl_times', to='items.template', verbose_name='Шаблон'),
        ),
    ]
