# Generated by Django 4.0.3 on 2023-09-08 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_blockevents_blockimgsteam_blockplace_imagesplace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='descriptionTemplateFirst',
            field=models.TextField(blank=True, max_length=255, verbose_name='Команда (Описание 1)'),
        ),
        migrations.AlterField(
            model_name='template',
            name='descriptionTemplateSesond',
            field=models.CharField(blank=True, max_length=255, verbose_name='Команда (Описание 2)'),
        ),
    ]
