# Generated by Django 4.0.3 on 2023-09-08 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_alter_template_descriptiontemplatefirst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='programm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programm_template', to='items.programms', verbose_name='Программа'),
        ),
    ]
