# Generated by Django 4.0.3 on 2023-09-08 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0017_template_programm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockimgsmall',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='imagesplace',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tagstimes',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Тэг'),
        ),
    ]
