# Generated by Django 4.0.3 on 2023-09-08 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0018_alter_blockimgsmall_name_alter_imagesplace_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockevents',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='blockevents',
            name='img',
            field=models.ImageField(blank=True, upload_to='image/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='blocktimes',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
