# Generated by Django 4.0.3 on 2023-09-08 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0019_alter_blockevents_description_alter_blockevents_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockimgsteam',
            name='name',
        ),
    ]
