# Generated by Django 4.0.3 on 2023-09-11 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0020_remove_blockimgsteam_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockplace',
            name='img',
        ),
        migrations.CreateModel(
            name='BlockImgPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='image/', verbose_name='Фотография')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images_place', to='items.template', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Место лагеря (фото)',
                'verbose_name_plural': 'Место лагеря (фото)',
                'ordering': ('-date_added',),
            },
        ),
        migrations.AddField(
            model_name='blockplace',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='imsPlace', to='items.blockimgplace', verbose_name='Фотографии'),
        ),
    ]
