# Generated by Django 4.0.3 on 2023-09-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0021_remove_blockplace_img_blockimgplace_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockimgplace',
            name='template',
        ),
        migrations.AddField(
            model_name='blockimgplace',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='blockimgplace',
            name='img',
            field=models.ImageField(blank=True, upload_to='image/', verbose_name='Фотография'),
        ),
    ]
