# Generated by Django 4.0.3 on 2023-09-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0022_remove_blockimgplace_template_blockimgplace_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='descriptionTemplateFirst',
            field=models.TextField(blank=True, max_length=1200, verbose_name='Команда (Описание 1)'),
        ),
    ]
