# Generated by Django 4.0.3 on 2023-09-12 17:32

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0023_alter_template_descriptiontemplatefirst'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('description', tinymce.models.HTMLField(verbose_name='Описание')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bquestions', to='items.template', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Место проведения блоки (Шаблон)',
                'verbose_name_plural': 'Место проведения блоки (Шаблон)',
            },
        ),
    ]
