# Generated by Django 4.0.3 on 2023-09-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0024_blockquestions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockquestions',
            options={'verbose_name': 'Вопрос ответ', 'verbose_name_plural': 'Вопрос ответ'},
        ),
        migrations.AddField(
            model_name='template',
            name='title_small',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название программы (Мал. часть)'),
        ),
    ]
