# Generated by Django 4.0.3 on 2023-09-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0025_alter_blockquestions_options_template_title_small'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Текст на главной')),
                ('name_disc', models.CharField(blank=True, max_length=255, verbose_name='Подзаголовок на главной')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Заголовок (на главной)',
                'verbose_name_plural': 'Заголовок (на главной)',
                'ordering': ('-date_added',),
            },
        ),
    ]
