# Generated by Django 4.0.3 on 2023-09-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0026_textmain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programms',
            name='date_added',
            field=models.DateTimeField(blank=True),
        ),
    ]
