# Generated by Django 4.0.3 on 2023-11-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0027_alter_programms_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='data_uchast',
            field=models.DateField(blank=True, verbose_name='Дата рождения участника'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='fio',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФИО участника'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='info_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Откуда узнали о нас'),
        ),
    ]
