# Generated by Django 4.0.3 on 2023-11-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0028_alter_reserve_data_uchast_alter_reserve_fio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='data_uchast',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения участника'),
        ),
    ]
